export { default as AdminLogin } from './AdminLogin';
export { default as Dashboard } from './Dashboard';
export { default as ProblemsManagement } from './ProblemsManagement';
export { default as BlogManagement } from './BlogManagement';
export { default as ProblemUpdate } from './ProblemUpdate';
export { default as UpdateUserByAdmin } from './UpdateUserByAdmin';
export { default as UserManagement } from './UserManagement';
export { default as ContestManagement } from './ContestManagement';
export { default as AddContest } from './AddContest';
